jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: tinovyatkin/action-check-deprecated-js-deps@v1
        with:
          root: packages
name: build
on:
  push:
    branches:
      - "**"
